version: '3'
services:
  ubuntu.test:
    build: ./ubuntu
    image: ubuntu-ssh
    hostname: server1.test
    ports:
      - "2224:22"
  centos.test:
    build: ./centos
    image: centos-ssh
    hostname: server2.test
    ports:
      - "2225:22"
