  GNU nano 2.9.3                                          setup-tomcat.yml                                                    

---
- name: setup tomcat
  hosts: all
  become: true
  tasks:
  - name: install java
    yum:
      name: java
      state: installed
    when: ansible_os_family == "RedHat"

  - name: install java on ubuntu
    apt:
      name: default-jdk
      state: present
    when: ansible_os_family == "Debian"

  - name: dowload tomcat packages
    get_url:
     url: http://mirror.funkfreundelandshut.de/apache/tomcat/tomcat-8/v8.5.51/bin/apache-tomcat-8.5.51.tar.gz
     dest: /opt

  - name: untar apache packages
    unarchive:
      src: /opt/apache-tomcat-8.5.51.tar.gz
      dest: /opt
      remote_src: yes

  - name: add execution permissions on startup.sh file
    file:
      path: /opt/apache-tomcat-8.5.51/bin/startup.sh
      mode: 0777

  - name: start tomcat services
    shell: nohup ./startup.sh
    args:
      chdir: /opt/apache-tomcat-8.5.51/bin
