---
- name: this playbook install httpd
  hosts: rhel
  become: true
  tasks:
  - name: install package
    yum:
      name: httpd
      state: installed

  - name: start httpd service
    service:
      name: httpd
      state: started
